# -*- coding: utf-8 -*-
"""insights_Kovai.co.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gw37vuTkTv_f4tuNglGu2cgPgSA88Sgu
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')

df = pd.read_csv('Daily_Public_Transport.csv')
df.head()

#Formatting the data
df['Date'] = pd.to_datetime(df['Date'])

columns_to_clean = ['Local Route', 'Light Rail', 'Rapid Route', 'School', 'Peak Service']
for col in columns_to_clean:
    df[col] = df[col].astype(str).str.replace(',', '')
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.dropna(subset=columns_to_clean, inplace=True)

# Add Weekday column
df['Weekday'] = df['Date'].dt.day_name()

columns_to_convert = ['Local Route', 'Light Rail', 'Rapid Route', 'School', 'Peak Service']

# Remove commas and convert to numeric
for col in columns_to_convert:
    df[col] = df[col].astype(str).str.replace(',', '')  # Remove commas
    df[col] = pd.to_numeric(df[col], errors='coerce')   # Convert to numbers (NaNs if it fails)

# Double-check types
df[columns_to_convert].dtypes

"""#**INSIGHT 1**:  Impact of COVID-19 Lockdowns and Public Holidays on Transport Usage
Canberra's lockdown spanned approximately nine weeks, from 12 August to 15 October 2021
“During the COVID-19 lockdown, School and Peak services fell to near-zero immediately, indicating no essential demand.
However, Local Route and Light Rail still retained some usage, likely by essential workers like healthcare and delivery staff.
This tells us: In future emergency or pandemic scenarios, the transport department should:

Pause School and Peak services

Keep Local Routes and Light Rail partially active with reduced frequency

Avoid running empty fleets and optimize costs during lockdown-like periods.”
"""

# Plot each service separately to compare impact
services = ['Local Route', 'Light Rail', 'Rapid Route', 'School', 'Peak Service']

plt.figure(figsize=(15,7))
for service in services:
    plt.plot(df_sorted['Date'], df_sorted[service], label=service)

# Add event shading
plt.axvspan(pd.to_datetime('2020-03-23'), pd.to_datetime('2020-05-15'), color='red', alpha=0.2, label='COVID Lockdown')
plt.axvspan(pd.to_datetime('2021-08-12'), pd.to_datetime('2021-10-15'), color='red', alpha=0.2, label='COVID Lockdown')


plt.title('Service-wise Drop in Usage During Lockdown')
plt.xlabel('Date')
plt.ylabel('Passenger Count')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""#**📊INSIGHT 2**

“Local Route services show significantly higher usage on weekdays compared to weekends — with up to a 40–60% drop on Saturdays and Sundays.
This suggests that Local Route demand is driven by work, school, and structured weekly routines.
Transport authorities can use this insight to optimize weekend fleet deployment — reducing service frequency or reallocating drivers during weekends — resulting in cost savings without affecting commuter satisfaction.”
"""

# Create 'Weekday' column (if not already created)
df['Weekday'] = df['Date'].dt.day_name()

# Group by weekday
local_weekday = df.groupby('Weekday')['Local Route'].mean()

# Reorder weekdays for correct order
order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
local_weekday = local_weekday.reindex(order)

# Plot
plt.figure(figsize=(10,5))
local_weekday.plot(kind='bar', color='skyblue')
plt.title('Average Local Route Usage by Weekday')
plt.xlabel('Weekday')
plt.ylabel('Average Passenger Count')
plt.grid(True)
plt.show()

"""#**📊INSIGHT 3**
**Leveraging Light Rail's Weekend Demand for Leisure-Oriented Growth**


> While most services like School and Rapid Route see steep drops on weekends, Light Rail maintains high usage, suggesting it's used for leisure, shopping, or tourism, not just commuting.

 Recommendation:

    Maintain or increase Light Rail service on Saturdays, especially around leisure areas.
    Offer weekend group/family passes and off-peak discounts.
    Partner with malls, events, or tourism boards for promotions.


"""

weekday_avg = df.groupby('Weekday')[['Local Route', 'Light Rail', 'Rapid Route', 'School', 'Peak Service']].mean()

weekday_avg = weekday_avg.reindex(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])

weekday_avg.plot(kind='bar', figsize=(12,6))
plt.title('Average Passengers by Weekday per Service Type')
plt.ylabel('Passenger Count')
plt.show()

"""##📊 Insight 4: COVID-19’s Lingering Footprint on Weekend Ridership Patterns

**What we observed:**
- Weekend ridership dropped significantly during 2020–2021 due to COVID-19 restrictions.
- Even post-pandemic, weekend usage shows slower recovery and high variability.
- Indicates that leisure and casual travel patterns haven’t fully bounced back.

**Actionable Recommendations:**
- Launch leisure-oriented campaigns in collaboration with local events or tourist spots.
- Adjust weekend operations with flexible schedules or smaller vehicles to match demand.
- Offer weekend fare discounts to attract families and casual riders.

"""

# Cell 6
df['Total_Ridership'] = df[columns_to_clean].sum(axis=1)
weekend_df = df[df['Weekday'].isin(['Saturday', 'Sunday'])]

plt.figure(figsize=(14,6))
plt.plot(weekend_df['Date'], weekend_df['Total_Ridership'], marker='o')
plt.title('Weekend Total Ridership Over Time')
plt.xlabel('Date')
plt.ylabel('Total Ridership')
plt.grid(True)
plt.tight_layout()
plt.show()